# Generated by Django 5.2 on 2025-04-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
